////
//// Created by Administrator on 2020/8/25.
////
//
//#ifndef CAMERA2_NATIVECOLORRENDER_H
//#define CAMERA2_NATIVECOLORRENDER_H
//
//
//class NativeColorRender {
//
//};
//
//
//#endif //CAMERA2_NATIVECOLORRENDER_H
//
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../Android/Sdk/ndk/16.1.4479499/sysroot/usr/include/jni.h"
/* Header for class com_android_camera2_gles_NativeColorRender */

#ifndef _Included_com_android_camera2_gles_NativeColorRender
#define _Included_com_android_camera2_gles_NativeColorRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_camera2_gles_NativeColorRender
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL onDrawFrame
        (JNIEnv *, jobject);

/*
 * Class:     com_android_camera2_gles_NativeColorRender
 * Method:    surfaceCreate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL surfaceCreate
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_android_camera2_gles_NativeColorRender
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL surfaceChanged
        (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
