///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
//#include "../../../../../../Android/Sdk/ndk/16.1.4479499/sysroot/usr/include/jni.h"
///* Header for class com_android_camera2_gles_NativeRender */
//
//#ifndef _Included_com_android_camera2_gles_NativeRender
//#define _Included_com_android_camera2_gles_NativeRender
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     com_android_camera2_gles_NativeRender
// * Method:    onDrawFrame
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_android_camera2_gles_NativeRender_onDrawFrame
//  (JNIEnv *, jobject);
//
///*
// * Class:     com_android_camera2_gles_NativeRender
// * Method:    surfaceChanged
// * Signature: (II)V
// */
//JNIEXPORT void JNICALL Java_com_android_camera2_gles_NativeRender_surfaceChanged
//  (JNIEnv *, jobject, jint, jint);
//
///*
// * Class:     com_android_camera2_gles_NativeRender
// * Method:    surfaceCreateColor
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_android_camera2_gles_NativeRender_surfaceCreateColor
//  (JNIEnv *, jobject);
//
///*
// * Class:     com_android_camera2_gles_NativeRender
// * Method:    drawColor
// * Signature: (Ljava/lang/Object;I)V
// */
//JNIEXPORT void JNICALL drawColor
//  (JNIEnv *, jobject, jobject, jint);
//
///*
// * Class:     com_android_camera2_gles_NativeRender
// * Method:    drawBitmap
// * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
// */
//JNIEXPORT void JNICALL drawBitmap
//  (JNIEnv *, jobject, jobject, jobject);
//
//#ifdef __cplusplus
//}
//#endif
//#endif
